services:
  php:
    build:
      context: .
      dockerfile: server/php/Dockerfile
    container_name: php
    volumes:
      - ./client:/var/www/client
      - ./.env:/var/www/client/.env:ro
      - vendor-volume:/var/www/client/vendor
    networks:
      - camagru
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    build:
      context: .
      dockerfile: server/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./client:/var/www/client
      - ./server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - camagru
    depends_on:
      - php
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - camagru
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - camagru
    restart: unless-stopped
    depends_on:
      - mariadb

networks:
  camagru:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  vendor-volume:
    driver: local