services:
  php:
    build:
      context: .
      dockerfile: server/php/Dockerfile
    container_name: php
    volumes:
      - ./client:/var/www/client
      - ./.env:/var/www/client/.env:ro
    networks:
      - camagru
    depends_on:
      - mariadb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: .
      dockerfile: server/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./client:/var/www/client
      - ./server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - camagru
    depends_on:
      - php
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - camagru
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - camagru
    restart: always
    depends_on:
      - mariadb

networks:
  camagru:
    driver: bridge

volumes:
  mariadb_data:
    driver: local