services:

nginx:
  build:
      context: .
      dockerfile: server/nginx/Dockerfile
  container_name: nginx
  ports:
      - "80:80"
  volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server/nginx/:/etc/nginx/sites-enabled/
  networks:
      - camagru

mariadb:
  image: mariadb:latest
  container_name: mariadb
  environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camagru
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  volumes:
      - ./server/mariadb/data:/var/lib/mysql
  networks:
      - camagru
  ports:
      - "3306:3306"
  restart: always

phpmyadmin:
  image: phpmyadmin
  container_name: phpmyadmin
  environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
  ports:
      - "8080:80"
  networks:
      - camagru
  restart: always
  depends_on:
      - mariadb

networks:
  camagru:
    driver: bridge

volumes:
  mariadb_data:
    driver: local