FROM nginx:1.27-alpine

RUN rm /etc/nginx/conf.d/default.conf

RUN apk update && apk add --no-cache openssl

RUN mkdir -p /var/log/nginx

COPY server/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]